# Generated by Django 4.2.4 on 2023-09-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen_Producto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/%Y%m', verbose_name='Imagen Producto'),
        ),
    ]
