# Generated by Django 4.2.6 on 2023-10-11 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_articulos_imagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='imagen_Producto',
        ),
        migrations.AddField(
            model_name='articulos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
