# Generated by Django 4.2.6 on 2023-10-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_articulos_imagen_producto_articulos_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='imagen_Producto',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/%Y%m', verbose_name='Imagen Producto'),
        ),
    ]
