# Generated by Django 4.2.6 on 2023-11-07 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_Reservas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_Personas', models.IntegerField(default=0, verbose_name='Cantidad Personas')),
                ('ubicacion_Mesa', models.CharField(choices=[('i1', 'I1'), ('i2', 'I2'), ('i3', 'I3'), ('i4', 'I4'), ('d1', 'D1'), ('d2', 'D2'), ('d3', 'D3'), ('d4', 'D4'), ('c1', 'C1'), ('c2', 'C2'), ('c3', 'C3')], default='cualquiera', verbose_name='Ubicacion Mesa')),
                ('fecha', models.DateField(null=True, verbose_name='fecha')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Cliente')),
            ],
        ),
    ]
