# Generated by Django 4.2.7 on 2023-11-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='estado_Reserva',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Denegado', 'Denegado')], default=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
