# Generated by Django 4.2.7 on 2023-11-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservas_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado_Reserva',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Denegado', 'Denegado')], default='Pendiente', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='ubicacion_Mesa',
            field=models.CharField(choices=[('Cualquiera', 'Cualquiera'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], default='Cualquiera', verbose_name='Ubicacion Mesa'),
        ),
    ]
