# Generated by Django 4.2.6 on 2023-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_reservas_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='nombre_Reserva',
            field=models.CharField(null=True, verbose_name='Nombre Reserva'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='ubicacion_Mesa',
            field=models.CharField(choices=[('Cualquiera', 'Cualquiera'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='Cualquiera', verbose_name='Ubicacion Mesa'),
        ),
    ]
