# Generated by Django 4.2.6 on 2023-11-07 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_articulos_imagen_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Mesero',
            fields=[
                ('id_Orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articulo_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.articulos', verbose_name='Articulos')),
                ('id_Usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Bodega',
            fields=[
                ('id_Orden_Bodega', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('tipo_Cantidad', models.CharField(choices=[('unidad', 'Unidad'), ('decena', 'Decena'), ('docena', 'Docena')], verbose_name='Tipo Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha Pedido Bodega')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articulos_Bodega_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.articulos', verbose_name='Articulos Pedido')),
                ('id_Usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_Inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_Inicial', models.IntegerField(verbose_name='Cantididad Inicial')),
                ('cantidad_Final', models.IntegerField(verbose_name='Cantididad Final')),
                ('fecha', models.DateField(verbose_name='Fecha Inventario')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_Articulos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.articulos', verbose_name='id Articulos')),
                ('pedidos_Bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido_bodega', verbose_name='pedido bodega')),
            ],
        ),
    ]
