# Generated by Django 4.2.7 on 2023-11-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_bodega_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_bodega',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha Pedido Bodega'),
        ),
        migrations.AlterField(
            model_name='pedido_bodega',
            name='tipo_Cantidad',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Decena', 'Decena'), ('Docena', 'Docena'), ('PacaX20', 'PacaX20'), ('PacaX24', 'PacaX24')], verbose_name='Tipo Cantidad'),
        ),
    ]
