# Generated by Django 4.2.7 on 2023-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_bodega_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_bodega',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Pedido Bodega'),
        ),
    ]
