# Generated by Django 4.2.7 on 2023-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_bodega_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_bodega',
            name='cantidad_Total',
            field=models.IntegerField(default=1, verbose_name='Cantidad total'),
            preserve_default=False,
        ),
    ]
