# Generated by Django 4.2.7 on 2023-11-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_bodega_cantidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad_TotalVenta',
            field=models.IntegerField(default=0, verbose_name='Cantidad total'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='total_Venta',
            field=models.IntegerField(default=0, verbose_name='Venta total'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_Final',
            field=models.IntegerField(default=0, verbose_name='Cantididad Final'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_Inicial',
            field=models.IntegerField(default=0, verbose_name='Cantididad Inicial'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Inventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='pedidos_Bodega',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido_bodega', verbose_name='pedido bodega'),
        ),
    ]
