# Generated by Django 4.2.7 on 2023-11-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_articulos_imagen_producto'),
        ('pedidos', '0007_inventario_cantidad_totalventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id_Articulos',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_Articulos_Inventario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.articulos', verbose_name='Articulo'),
        ),
    ]
