# Generated by Django 4.2.4 on 2023-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(choices=[('cliente', 'Cliente'), ('Mesero', 'Mesero'), ('Dj', 'Dj'), ('Proveedor', 'Proveedor'), ('Administrador', 'Administrador')], default='cliente', verbose_name='Tipo Usuario')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido_Usuario', models.CharField(max_length=30, verbose_name='Apellido')),
                ('genero_Usuario', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], verbose_name='Genero')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('estado_Civil', models.CharField(choices=[('soltero', 'Soltero'), ('comprometido', 'Comprometido')], verbose_name='estado civil')),
                ('telefono', models.CharField(null=True, verbose_name='Telefono')),
                ('pregunta_Seguridad', models.CharField(choices=[('nombre de tu mascota', 'nombre de tu mascota'), ('color favorito', 'color favorito'), ('colegio donde estudiaste', 'colegio donde estudiaste')], default=' - - - - - - - - - -', verbose_name='Preguntas de Seguridad')),
                ('respuesta_Pregunta', models.CharField(null=True, verbose_name='Respuesta a Pregunta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
