# Generated by Django 4.2.7 on 2023-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Mesero', 'Mesero'), ('Dj', 'Dj'), ('Proveedor', 'Proveedor'), ('Administrador', 'Administrador')], default='cliente', verbose_name='Tipo Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado_Civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Comprometido', 'Comprometido')], verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero_Usuario',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], verbose_name='Genero'),
        ),
    ]
