# Generated by Django 4.2.7 on 2023-11-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cargo_alter_user_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Mesero', 'Mesero'), ('Dj', 'Dj'), ('Proveedor', 'Proveedor'), ('Administrador', 'Administrador')], default='Cliente', verbose_name='Tipo Usuario'),
        ),
    ]
