# Generated by Django 4.2.7 on 2023-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado_Civil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pregunta_Seguridad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='respuesta_Pregunta',
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Mesero', 'Mesero'), ('Dj', 'Dj'), ('Proveedor', 'Proveedor'), ('Administrador', 'Administrador')], verbose_name='Tipo Usuario'),
        ),
    ]
