# Generated by Django 4.2.6 on 2023-11-23 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_edad_remove_user_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Mesero', 'Mesero'), ('Dj', 'Dj'), ('Proveedor', 'Proveedor'), ('Administrador', 'Administrador'), ('Cliente', 'Cliente')], default='Cliente', verbose_name='Tipo Usuario'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado_Civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Comprometido', 'Comprometido')], verbose_name='estado civil')),
                ('pregunta_Seguridad', models.CharField(choices=[('nombre de tu mascota', 'nombre de tu mascota'), ('color favorito', 'color favorito'), ('colegio donde estudiaste', 'colegio donde estudiaste')], default=' - - - - - - - - - -', verbose_name='Preguntas de Seguridad')),
                ('respuesta_Pregunta', models.CharField(null=True, verbose_name='Respuesta a Pregunta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
