# Generated by Django 4.2.4 on 2023-09-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_Musica', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.CharField(max_length=30, verbose_name='Titulo Cancion')),
                ('genero', models.CharField(blank=True, max_length=30, null=True, verbose_name='Genero Musical')),
                ('nombre_Artista', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Artista')),
            ],
        ),
    ]
