# Generated by Django 4.2.4 on 2023-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='cancion',
            field=models.CharField(max_length=50, verbose_name='Titulo Cancion'),
        ),
    ]
